# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f947ef93e104e836ab2657f0fd2fb81e52decd12c7092f0e2a717c792eb64f65d16e9648f2edd095d3c541e462cc6835a5e2edac098f882bd6b7c16b09fdb8b7

test:
  secret_key_base: 4fbaf16047fc74011162a785f1cf6598b1ae40c458493b3cf3c5273084ab88881617a0e7d6ee688ee13e12676a16f5c44898a59cf19a561f7ef985aa00eb7d1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
